PostComment/Messaging/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),

)

urlpatterns = [
    path('admin/', admin.site.urls),
    #re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    #re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('api/posts/',include('posts.api.urls', namespace='api-upload')),
    #path('posts/', include('posts.urls')),
    #path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_URL)
else:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

PostComment/posts/api/urls.py
from .views import MessageReadUpdate, MessageListAPIView, MessageCreate

from django.contrib import admin
from django.urls import path, include, re_path

app_name = 'post'

urlpatterns = [
    path('', MessageListAPIView.as_view(), name='message-list'),
    path('create/', MessageCreate.as_view(), name='message-create'),
    path('<int:Collaborate_Messaging_A00_Rec>/', MessageReadUpdate.as_view(), name='message-read'),
    #path('module/<int:pk>/', ModuleRead.as_view(), name='module-read'),
    #path('contact/<int:pk>/', ContactRead.as_view(), name='contact-read'),
]

PostComment/posts/urls.py
from django.urls import path, include, re_path
from . import views

app_name ='posts'

urlpatterns = [
    path('', views.posts_home, name='index'),
    path('<int:Collaborate_Messaging_A00_Rec>/', views.posts_detail, name='detail'),
    path('create/', views.posts_create, name= 'create'),
    path('<int:Collaborate_Messaging_A00_Rec>/create_reply/', views.post_reply, name='reply'),


]

PostComment/posts/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.urls import reverse

# Create your models here.

class Collaborate_Messaging_A00(models.Model):

    Collaborate_Messaging_A00_Rec = models.AutoField(primary_key=True)
    POST ='POST'
    REPLY='REPLY'
    MESSAGE_TYPE_CHOICES = [
        (POST, 'Post'),
        (REPLY, 'Reply'),

    ]
    messageType = models.CharField(max_length=10, choices= MESSAGE_TYPE_CHOICES, default=POST, db_column='Message_Type')
    parentPostId = models.ForeignKey('posts.Collaborate_Messaging_A00', on_delete=models.SET_NULL, null=True, blank=True)
    message = models.TextField()
    dateTimeStamp = models.DateTimeField(auto_now=True, auto_created=True)

    def __str__(self):
        return 'Collaborate_Messaging_A00_Rec' + str(self.Collaborate_Messaging_A00_Rec)

    def get_absolute_url(self):
        return reverse("detail", kwargs={"Collaborate_Messaging_A00_Rec": self.Collaborate_Messaging_A00_Rec})

"""
class Employee(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE,)
    employee_no = models.IntegerField()
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    address = models.CharField(max_length=250)


    def __str__(self):
        return self.first_name + '   ' + self.last_name

"""

PostComment/posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget

from .models import Collaborate_Messaging_A00

class PostForm(forms.ModelForm):
    message = forms.CharField(widget=PagedownWidget)

    class Meta:
        model = Collaborate_Messaging_A00
        fields = ["message"]

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Collaborate_Messaging_A00
        fields = ["message"]

PostComment/posts/api/views.py
from rest_framework import generics
from posts.models import Collaborate_Messaging_A00
from .serializers import FUMSerializer,  MessageListSerializer, MessageCreateSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django.db.models import Q

class MessageCreate(generics.CreateAPIView):
    queryset = Collaborate_Messaging_A00.objects.all()
    lookup_field = 'Collaborate_Messaging_A00_Rec'
    serializer_class = MessageCreateSerializer

    def get_queryset(self):
        #check=Collaborate_Files_A00.objects.values_list('collaborate_files_a00_rec', 'file_name')
        #print(check) #to be imported in a repository
        return Collaborate_Messaging_A00.objects.all()

class MessageReadUpdate(generics.RetrieveUpdateAPIView):
    lookup_field = 'Collaborate_Messaging_A00_Rec'
    serializer_class = FUMSerializer

    def get_queryset(self):
        return Collaborate_Messaging_A00.objects.all()



class MessageListAPIView(generics.ListAPIView):
    serializer_class = MessageListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['message', 'messageType', 'dateTimeStamp',]

    def get_queryset(self, *args, **kwargs):
        queryset_list = Collaborate_Messaging_A00.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(
                Q(message__icontains=query)|
                Q(messageType__icontains=query)|
                Q(dateTimeStamp__icontains=query)

            ).distinct()
        return queryset_list

PostComment/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Collaborate_Messaging_A00, Employee
from django.contrib.auth import authenticate, login
from .forms import PostForm, ReplyForm
from django.contrib import messages
from django.db.models import Q

# Create your views here.
"""
def posts_home(request):
    post = Collaborate_Messaging_A00.objects.all()
    query = request.GET.get("q")
    if query:
        post = post.filter(
            Q(messageType__icontains=query) |
            Q(dateTimeStamp__icontains=query)
        ).distinct()

        return render(request, 'posts/index.html', {
            'post': post,

        })
    else:
        return render(request, 'posts/index.html', {'post': post})

def posts_detail(request, Collaborate_Messaging_A00_Rec):
    post = get_object_or_404(Collaborate_Messaging_A00, Collaborate_Messaging_A00_Rec=Collaborate_Messaging_A00_Rec)

    return render(request, 'posts/detail.html', {'post': post})




def posts_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.save()


        return render(request, 'posts/detail.html', {'post': post})
    context = {
        "form": form, }
    return render(request, 'posts/form.html', context)

def post_reply(request, Collaborate_Messaging_A00_Rec):
    form = ReplyForm(request.POST or None)
    post = get_object_or_404(Collaborate_Messaging_A00, Collaborate_Messaging_A00_Rec=Collaborate_Messaging_A00_Rec)



    if form.is_valid():
        reply = form.save(commit=False)
        reply.save()

        return render(request, 'posts/detail.html', {'post': post})
    context = {'post': post, 'form': form, }
    return render(request, 'posts/create_reply.html', context)
"""

PostComment/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset ="UTF-8">
  <title>{% block title %}PostComment{% endblock %}</title>
  <!-- Loads the path to your static files -->
  {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet" type='text/css'>
  <link rel= "stylesheet" type ="text/css" href="{% static 'posts/style.css'%}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src= "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script src="{% static 'Home/js/main.js' %}"></script>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'posts:index' %}">PostComment</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'posts:create' %}"><span class="glyphicon glyphicon-plus-sign"></span> Add Post</a></li>
          <li><a href=""><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>
{% block body %}

{% endblock %}
</head>
<body>


</body>
</html>

PostComment/posts/templates/posts/create_reply.html
{% extends 'posts/base.html' %}
{% block title %}{{ post.message }}{% endblock %}
{% block body %}


<div class="container-fluid">

    <div class="row">

        <!-- Post -->
        <div class="col-sm-4 col-md-90">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'posts:detail' post.Collaborate_Messaging_A00_Rec %}"></a>
                    <h1>{{ post.message }}</h1>
                    <h4>{{ post.messageType }}</h4>
                    <h5>{{ post.dateTimeStamp }}</h5>
                </div>
                <ul class="nav nav-pills" style="margin-bottom: 30px;">

                    <li role="presentation"><a href="">Add Reply</a></li>
                </ul>
                <!-- Reply -->
                <div class="panel-body">
                    <h3>Add a New Reply</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% include 'posts/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

PostComment/posts/templates/posts/detail.html
{% extends 'posts/base.html' %}
{% block title %}{{ post.message }}{% endblock %}
{% block body %}


<div class="container-fluid">

    <div class="row">

        <!-- Left Post Info -->
        <div class="col-sm-4 col-md-90">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'posts:detail' post.Collaborate_Messaging_A00_Rec %}"></a>
                    <h1>{{ post.message }}</h1>
                    <h4> {{ post.messageType }}</h4>
                    <h5>{{ post.dateTimeStamp }}</h5>
                </div>
                <ul class="nav nav-pills" style="margin-bottom: 30px;">

                    <li role="presentation"><a href="{% url 'posts:reply' post.Collaborate_Messaging_A00_Rec %}">Add Reply</a></li>
                </ul>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Replies</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    {% for post in post.Collaborate_Messaging_A00_set.all %}
                        {{ post.message }}<br/>
                    {% endfor %}

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

PostComment/posts/templates/posts/form.html
{% extends 'posts/base.html' %}
{% block title %}Add a Post{% endblock %}

{% block body %}


<div class="container-fluid" >

    <div class="row">

       <div class="col-sm-8 col-md-9">
           <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Post</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal"  role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% include 'posts/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>


                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

PostComment/posts/templates/posts/form_template.html
{% for field in form %}
    <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="message">{{field.label_tag}}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

PostComment/posts/templates/posts/index.html
{% extends 'posts/base.html' %}


{% block body %}
<div class="post-container container-fluid">

    <!-- Post -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Hello, {{ user.username }}</h3>
        </div>
        {% if post %}
            {% for posts in post %}
                <div class="col-sm-10 col-lg-20">
                    <div class="thumbnail">

                        <div class="caption">
                            <h3>{{ posts.message }}</h3>
                            <h3>{{ posts.dateTimeStamp }}</h3>

                            <!-- View Details -->
                            <a href="{% url 'posts:detail' posts.Collaborate_Messaging_A00_Rec %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'posts:create' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Post
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}